### ISSUE TITLE
bug : the wing panel hides 

### ISSUE THREAD

**Issue by andirsun** [rbribeiro/wingpanel-indicator-dropbox#1] opened 2020-05-20 01:42 UTC
How can i uninstall the .dev file ? or how can i fix it ? 
![Screen record from 2020-05-19 20 39 43](https://user-images.githubusercontent.com/22928302/82395432-2b4fe800-9a11-11ea-8521-ed973fb69710.gif)

**Comment by rbribeiro** [comment] 2020-05-20 02:15
How did you install it? If you have used a GUI tool like Eddy, just open the .deb file again and hit uninstall.

The wingpanel keeps hiding or it does this just once? Another question, do you have the Dropbox CLI installed? because I've seen from your screenshot and it looks like you don't have it. The indicator requires it...

**Comment by andirsun** [comment] 2020-05-20 02:23
> How did you install it? If you have used a GUI tool like Eddy, just open the .deb file again and hit uninstall.
> 
> The wingpanel keeps hiding or it does this just once? Another question, do you have the Dropbox CLI installed? because I've seen from your screenshot and it looks like you don't have it. The indicator requires it...

Hi the wingpanel keeps hiding. Yes I install dropbox cli but i didn sign in.

**Comment by rbribeiro** [comment] 2020-05-20 02:28
Probably this is the problem. The indicator checks information on the dropbox folder, but since you didn't sign in, this information does not exists... maybe it is getting a segmentation fault error... I will check that latter. If you want to use the indicator you must have the dropbox working first.

you can uninstall the indicator running `sudo dpkg -r com.github.rbribeiro.wingpanel-indicator-dropbox `

thank you!

**Comment by andirsun** [comment] 2020-05-20 03:07
> Probably this is the problem. The indicator checks information on the dropbox folder, but since you didn't sign in, this information does not exists... maybe it is getting a segmentation fault error... I will check that latter. If you want to use the indicator you must have the dropbox working first.
> 
> you can uninstall the indicator running `sudo dpkg -r com.github.rbribeiro.wingpanel-indicator-dropbox `
> 
> thank you!

Okey, please if you fix the bug , attach the commit here and I will download and install again, and if your push into app center I can pay for it.

**Comment by rbribeiro** [comment] 2020-05-20 03:14
> > Probably this is the problem. The indicator checks information on the dropbox folder, but since you didn't sign in, this information does not exists... maybe it is getting a segmentation fault error... I will check that latter. If you want to use the indicator you must have the dropbox working first.
> > you can uninstall the indicator running `sudo dpkg -r com.github.rbribeiro.wingpanel-indicator-dropbox `
> > thank you!
> 
> Okey, please if you fix the bug , attach the commit here and I will download and install again, and if your push into app center I can pay for it.

I'm checking what is happening. It would be good if I could see the error message the indicator is printing on the console. One way is install the indicator and then kill the wingpanel twice by running twice `killall wingpanel` then run the wingpanel in the console again running `wingpanel`. 

When the wingpanel closes it will print an error message in the console. With this error I can have a better idea about what is going on.

**Comment by dcervenkov** [comment] 2020-05-24 13:45
@rbribeiro I've installed your package and observe the same behavior as @andirsun - the wingpanel crashes within a few seconds. I am logged in to Dropbox and the indicator does show recently synced files correctly, for the few seconds it works.

I ran `wingpanel` from a console, but the only output is `[1]    1203 segmentation fault  wingpanel`. Removing your package fixes the issue.

**Comment by rbribeiro** [comment] 2020-05-24 15:21
> @rbribeiro I've installed your package and observe the same behavior as @andirsun - the wingpanel crashes within a few seconds. I am logged in to Dropbox and the indicator does show recently synced files correctly, for the few seconds it works.
> 
> I ran `wingpanel` from a console, but the only output is `[1] 1203 segmentation fault wingpanel`. Removing your package fixes the issue.

Thank you for your feedback! I'm still trying to figure it out. I've some ideas, but I still don't know how to reproduce the issue since the indicator has been working perfectly fine in my computer.

**Comment by andirsun** [comment] 2020-05-24 16:45
> > @rbribeiro I've installed your package and observe the same behavior as @andirsun - the wingpanel crashes within a few seconds. I am logged in to Dropbox and the indicator does show recently synced files correctly, for the few seconds it works.
> > I ran `wingpanel` from a console, but the only output is `[1] 1203 segmentation fault wingpanel`. Removing your package fixes the issue.
> 
> Thank you for your feedback! I'm still trying to figure it out. I've some ideas, but I still don't know how to reproduce the issue since the indicator has been working perfectly fine in my computer.

install in a vm and see if happens with you

**Comment by rbribeiro** [comment] 2020-05-27 19:07
@andirsun @dcervenkov I think I fixed the problem. Well, at least it also works in a VM, where I was able to reproduce the bug you have pointed out.

**Comment by andirsun** [comment] 2020-05-27 19:13
> @andirsun @dcervenkov I think I fixed the problem. Well, at least it also works in a VM, where I was able to reproduce the bug you have pointed out.

I can test again and report you back

**Comment by dcervenkov** [comment] 2020-05-28 12:51
@rbribeiro I tried the new `deb` from the packages directory. At first, it seemed to work; however, after a few minutes, the wingpanel crashed. After starting it again, it crashed within seconds, just like before. The only message is `[1]    30294 segmentation fault  wingpanel`.

**Comment by rbribeiro** [comment] 2020-05-28 14:28
> @rbribeiro I tried the new `deb` from the packages directory. At first, it seemed to work; however, after a few minutes, the wingpanel crashed. After starting it again, it crashed within seconds, just like before. The only message is `[1] 30294 segmentation fault wingpanel`.

@dcervenkov, Does it crash while it is syncing files?

**Comment by dcervenkov** [comment] 2020-05-28 14:39
Nope, I'm pretty sure there was no syncing going on at the time. Running `wingpanel` under `gdb` with your extension installed shows `Thread 12 "compare-dir" received signal SIGSEGV, Segmentation fault.` Maybe related to this? https://github.com/rbribeiro/wingpanel-indicator-dropbox/blob/74b9e9f458d86c676208e36aa34bce05206e8db1/src/Services/DirMonitor.vala#L55

**Comment by rbribeiro** [comment] 2020-05-28 14:54
> Nope, I'm pretty sure there was no syncing going on at the time. Running `wingpanel` under `gdb` with your extension installed shows `Thread 12 "compare-dir" received signal SIGSEGV, Segmentation fault.` Maybe related to this?
> 
> https://github.com/rbribeiro/wingpanel-indicator-dropbox/blob/74b9e9f458d86c676208e36aa34bce05206e8db1/src/Services/DirMonitor.vala#L55

Great @dcervenkov ! Now I think I have an idea about what is going on. 
This DirMonitor service keeps looking for chances in the Dropbox folder in order to refresh the list of recent activity. I tried to use the dir_monitor method present in the GLib, but it monitors only changes in the specific directory. If a change happens in a subdir, it doesn't emit anything.

So, what I do is to run through the directory tree comparing the modification date of each file/dir and then I emit a signal when anything has been modified. I have to do this comparison in a new thread to avoid it freezes the GUI.

If you have any better idea about how to do this, please let me know. Maybe this is a standard thing...

**Comment by dcervenkov** [comment] 2020-05-28 15:30
Well, the standard Linux way of monitoring the filesystem for changes would be [inotify](https://www.man7.org/linux/man-pages/man7/inotify.7.html). I'm not very familiar with GLib - maybe the `dir_monitor` is just a frontend for `inotify`?

> So, what I do is to run through the directory tree comparing the modification date of each file/dir and then I emit a signal when anything has been modified. I have to do this comparison in a new thread to avoid it freezes the GUI.

I guess you watch only the dirs and once a change in a dir is detected, then look at the files, right? Other than that, your approach seem reasonable to me.

**Comment by rbribeiro** [comment] 2020-05-28 17:13
> I guess you watch only the dirs and once a change in a dir is detected, then look at the files, right? Other than that, your approach seem reasonable to me.

This is exactly what I do. I've read the inotify documentation and it has the same problem I've mentioned. A possible solution would be run through the tree and add one watch at each directory. However there is a max number of watch one can creates and it may take too much time to create all those watchers.

Do you think creating a lot of threads could be the problem? At every 3 seconds I create a new thread and run through the tree checking for changes. I don't know what could happen if running through the tree takes more than 3 seconds. Do you have many files in your dropbox? Because I have close to 2.000 and my laptop has a SSD. This could be the reason why the indicator has worked perfectly fine for me.

**Comment by dcervenkov** [comment] 2020-05-29 14:13
> A possible solution would be run through the tree and add one watch at each directory.

I think you have to do that in either case.

> Do you think creating a lot of threads could be the problem? At every 3 seconds I create a new thread and run through the tree checking for changes. I don't know what could happen if running through the tree takes more than 3 seconds.

¯\_(ツ)_/¯ What about extending the interval to 30 seconds to see if that is the culprit?

> Do you have many files in your dropbox? Because I have close to 2.000 and my laptop has a SSD. This could be the reason why the indicator has worked perfectly fine for me.

Yeah, I've got ~23k files in there.

**Comment by rbribeiro** [comment] 2020-05-29 15:24
> ¯_(ツ)_/¯ What about extending the interval to 30 seconds to see if that is the culprit?
> 
I've tried another approach. Now, the code doesn't run through the directory tree if there is another thread running. Let's see!

**Comment by dcervenkov** [comment] 2020-05-31 10:09
OK, it's not crashing now! However, every ~3 seconds the `wingpanel` (and `gvfsd-metadata`) consumes a massive amount of resources - up to 70% of 4 cores. When I uninstall the package and restart `wingpanel`, it's back to ~0.

**Comment by rbribeiro** [comment] 2020-05-31 14:06
> OK, it's not crashing now! However, every ~3 seconds the `wingpanel` (and `gvfsd-metadata`) consumes a massive amount of resources - up to 70% of 4 cores. When I uninstall the package and restart `wingpanel`, it's back to ~0.
Great! 

Yeah, I'm aware of that and I think I have a solution. The problem is that I'm sorting the files in the folder by their modification/creation date. If you have just created a lot of files of modified a lot of them, the sort method (I'm doing a quick sort) is incredibly resource consuming.

I will push the fix very soon. I hope to hear from you then.

**Comment by rbribeiro** [comment] 2020-06-01 23:55
@andirsun @dcervenkov hey guys! Have you tried the newest version? I'm curious to see if it finally works!

**Comment by andirsun** [comment] 2020-06-02 01:20
> @andirsun @dcervenkov hey guys! Have you tried the newest version? I'm curious to see if it finally works!

I'm gonna try and report later . Thanks bro

**Comment by dcervenkov** [comment] 2020-06-02 11:10
Curious. The first ~30 seconds I saw `wingpanel` CPU spikes to 11%, after a while the spikes grew to 70%.

I just realized something - you recently wrote
>At every 3 seconds I create a new thread and run through the tree checking for changes.

I currently don't have time to look at your code, but that sounds like you are actively looking for changes. The `inotify` subsystem was made to avoid the need for that. From the `inotify` Wikipedia page:
> One major use is in desktop search utilities like Beagle, where its functionality permits reindexing of changed files without scanning the filesystem for changes every few minutes, which would be very inefficient.

Basically, you set up the watches, and then you can use a single thread that listens for changes in all the watched dirs simultaneously while eating 0% CPU. I think [this article](https://www.linuxjournal.com/article/8478) can be helpful for understanding how it works.

I assume the GLib approach works the same way.

**Comment by rbribeiro** [comment] 2020-06-10 03:29
> Curious. The first ~30 seconds I saw `wingpanel` CPU spikes to 11%, after a while the spikes grew to 70%.
> 
> I just realized something - you recently wrote
> 
> > At every 3 seconds I create a new thread and run through the tree checking for changes.
> 
> I currently don't have time to look at your code, but that sounds like you are actively looking for changes. The `inotify` subsystem was made to avoid the need for that. From the `inotify` Wikipedia page:
> 
> > One major use is in desktop search utilities like Beagle, where its functionality permits reindexing of changed files without scanning the filesystem for changes every few minutes, which would be very inefficient.
> 
> Basically, you set up the watches, and then you can use a single thread that listens for changes in all the watched dirs simultaneously while eating 0% CPU. I think [this article](https://www.linuxjournal.com/article/8478) can be helpful for understanding how it works.
> 
> I assume the GLib approach works the same way.

Thank you for the explanation! I will close this issue and try to push a new version with the approach you have suggested.

**Closed as completed by rbribeiro** 2020-06-10 03:29 UTC
