### ISSUE TITLE
Installation Failed on Elementary OS 6

### ISSUE THREAD

**Issue by chinmayrajyaguru** [rbribeiro/wingpanel-indicator-dropbox#16] opened 2021-09-05 11:49 UTC
Error:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'com.github.rbribeiro.wingpanel-indicator-dropbox' instead of './com.github.rbribeiro.wingpanel-indicator-dropbox_0.1_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 com.github.rbribeiro.wingpanel-indicator-dropbox : Depends: libwingpanel-2.0-0 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by JeysonFlores** [comment] 2021-09-05 20:28
It seems that is a duplicate of #15 . Can you try that solution and see what happens?

**Closed as completed** 2021-10-02 16:57 UTC
